# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78d24e4817afbb2518990e70bc7df2fb5f0448155c9b65c87664f2996932590febef0e0562f01e2ee5842f7ed216cc112c5bb189eee292d0a78c8b1805fb1bd3

test:
  secret_key_base: 4df7b4a03d23b2c52183024f511d483a50a51ef268496990189393b6c42df8cbff60165ac3ca256abe58db753e3915e8ee0851d9a3c600a793e2403b7d423576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
